import 'package:flutter/material.dart';

class APIConstants {
  static final String baseUrl = 'https://it-searcj-job-app-be.onrender.com';
  static final String getCategories_endpoint = 'auth/categories';
  static final String postJob_endpoint = 'jobs';
  static final String token = 'eyJhbGciOiJIUzI1NiIsImtpZCI6ImVJclVSTTROUldPb3FDS2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3F3aWxkZGFxbnJ6bnFiaHVza3p4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2NzRjNzIwNC0xMDZlLTRkN2YtOGRjMy0zZjYzODlkMGFhOGUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1MTcyMDI3LCJpYXQiOjE3NDUxNjg0MjcsImVtYWlsIjoibGVuZ29jYW5ocHluZTM2M0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl0sInJvbGUiOiJyZWNydWl0ZXIifSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImxlbmdvY2FuaHB5bmUzNjNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNjc0YzcyMDQtMTA2ZS00ZDdmLThkYzMtM2Y2Mzg5ZDBhYThlIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDUxNjg0Mjd9XSwic2Vzc2lvbl9pZCI6IjQ2ZTZkMWM3LThmNzktNDdjYi05Njg5LTVkY2FmMmQyYTE2ZSIsImlzX2Fub255bW91cyI6ZmFsc2V9.27smraV92e-yiKZQcxSnjQw9c6NQ4aGVNjYviSMX-sI';
  static final String getApplications_recruiter_endpoint1 = 'jobs';
  static final String getApplications_recruiter_endpoint2 = 'applications';
  static final String getJob_endpoint = 'jobs';
  static final String responseJobApplication_endpoint = 'applications/process';
  static final Color successColor_toast = Colors.green;
  static final Color errorColor_toast = Colors.red;
}